# Site Info
title: Outer Heaven
tagline: 'Coding posts from a MGS fan'
description: 'Coding, mostly in JS.'
url: http://anilanar.github.io

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Anıl Anar
  description: <strong>Software engineer</strong>.
  gravatar: e764c6855517b86d8c7b0970cae65f6c # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/aanar
    github:    https://github.com/anilanar
    # facebook:  <hide>
    twitter:   https://twitter.com/mostruash
    email:     http://www.google.com/recaptcha/mailhide/d?k=01bORbraFoTrT6KYNphpMtVQ==&c=TUK07A9hq1kBPm87qL4sCcbPgaFYMzQH6xWJvr-16RQ=

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'anilanar' # leave blank if you don't want disqus

